name: Auto Update NSE Data

on:
  schedule:
    # Run every 5 minutes during market hours
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Run NSE data scraper
      run: |
        python get_nse_data.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add nse_data_updater.js
        git commit -m "Auto-update NSE data $(date)" || echo "No changes to commit"
        git push
